"""
Configuration file generator for Pi-hole and Unbound.
Adapted from CLI version with web-specific enhancements.
"""

from typing import Dict, Any, List
from datetime import datetime
from pathlib import Path

from backend.models import ConfigFile


class ConfigGenerator:
    """Generates configuration files based on wizard settings."""

    def preview_all(self, config: Dict[str, Any]) -> List[ConfigFile]:
        """Generate all config files and return them for preview (no file writing)."""
        files = []

        if config.get("deployment") == "docker":
            files.append(ConfigFile(
                filename="docker-compose.yml",
                content=self.generate_docker_compose(config),
                description="Docker Compose file to run Pi-hole and Unbound containers"
            ))
            files.append(ConfigFile(
                filename=".env",
                content=self.generate_env_file(config),
                description="Environment variables for Docker (edit password here)"
            ))

        if config.get("enable_unbound", True):
            files.append(ConfigFile(
                filename="unbound/pi-hole.conf",
                content=self.generate_unbound_config(config),
                description="Unbound recursive DNS resolver configuration"
            ))

        files.append(ConfigFile(
            filename="SETUP.md",
            content=self.generate_instructions(config),
            description="Step-by-step setup instructions customized for your config"
        ))

        return files

    def get_commands_to_run(self, config: Dict[str, Any]) -> List[str]:
        """Return list of commands that will be executed during installation."""
        commands = []

        if config.get("deployment") == "docker":
            commands.append("docker-compose pull  # Download Pi-hole and Unbound images")
            commands.append("docker-compose up -d  # Start containers in background")
            commands.append("docker-compose ps  # Verify containers are running")
        else:
            commands.append("curl -sSL https://install.pi-hole.net | bash  # Install Pi-hole")
            if config.get("enable_unbound", True):
                commands.append("apt install unbound -y  # Install Unbound")
                commands.append("cp unbound/pi-hole.conf /etc/unbound/unbound.conf.d/")
                commands.append("systemctl restart unbound")

        return commands

    def save_all(self, config: Dict[str, Any], output_dir: Path) -> List[str]:
        """Generate and save all config files to disk. Returns list of created files."""
        output_dir.mkdir(parents=True, exist_ok=True)
        created_files = []

        files = self.preview_all(config)

        for file in files:
            file_path = output_dir / file.filename
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(file.content)
            created_files.append(str(file_path))

        # Also save the config for reference
        import json
        config_path = output_dir / "wizard-config.json"
        config_path.write_text(json.dumps(config, indent=2))
        created_files.append(str(config_path))

        return created_files

    def generate_docker_compose(self, config: Dict[str, Any]) -> str:
        """Generate docker-compose.yml for Pi-hole (and optionally Unbound)."""

        pihole_dns = "127.0.0.1#5335" if config.get("enable_unbound", True) else self._get_upstream_dns(config)

        compose = f"""# Pi-hole & Unbound Docker Configuration
# Generated by Pi-hole Wizard on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
#
# Usage:
#   docker-compose up -d
#
# Web interface: http://{config.get("pihole_ip", "localhost")}/admin

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "${{TZ:-America/New_York}}"
      WEBPASSWORD: "${{WEBPASSWORD:-}}"
      PIHOLE_DNS_: "{pihole_dns}"
      DNSSEC: "{'true' if config.get('enable_unbound', True) else 'false'}"
      REV_SERVER: "{'true' if config.get('dhcp_enabled', False) else 'false'}"
"""

        if config.get("dhcp_enabled", False):
            compose += f"""      REV_SERVER_CIDR: "{self._get_cidr(config.get('pihole_ip', '192.168.1.2'))}"
      REV_SERVER_TARGET: "{config.get('dhcp_router', '192.168.1.1')}"
      REV_SERVER_DOMAIN: "local"
"""

        if not config.get("ipv6", False):
            compose += """      IPv6: "false"
"""

        compose += """    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
"""

        if config.get("enable_unbound", True):
            compose += """    depends_on:
      - unbound
    networks:
      - pihole_net

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: unbound
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/custom.conf.d:ro
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
"""
        else:
            compose += """    networks:
      - pihole_net

networks:
  pihole_net:
    driver: bridge
"""

        return compose

    def generate_env_file(self, config: Dict[str, Any]) -> str:
        """Generate .env file for docker-compose."""

        password = config.get('web_password') or 'changeme'

        return f"""# Pi-hole Environment Configuration
# Generated by Pi-hole Wizard

# Timezone (adjust to your location)
TZ=America/New_York

# Web interface password
# IMPORTANT: Change this to a secure password!
WEBPASSWORD={password}

# Pi-hole IP address (for reference)
PIHOLE_IP={config.get('pihole_ip', '192.168.1.2')}
"""

    def generate_unbound_config(self, config: Dict[str, Any]) -> str:
        """Generate Unbound configuration optimized for Pi-hole."""

        ipv6_setting = "yes" if config.get("ipv6", False) else "no"

        return f"""# Unbound configuration for Pi-hole
# Generated by Pi-hole Wizard on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
#
# This configures Unbound as a recursive DNS resolver.
# Pi-hole forwards queries to Unbound on port 5335.

server:
    # Logging (set verbosity to 1 or 2 for debugging)
    verbosity: 0

    # Network interface settings
    interface: 0.0.0.0
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # IPv6 settings
    do-ip6: {ipv6_setting}
    prefer-ip6: no

    # Security and hardening
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    harden-algo-downgrade: yes
    harden-large-queries: yes
    harden-short-bufsize: yes

    # Privacy settings
    use-caps-for-id: no
    qname-minimisation: yes
    qname-minimisation-strict: no

    # Performance tuning
    num-threads: 1
    msg-cache-slabs: 2
    rrset-cache-slabs: 2
    infra-cache-slabs: 2
    key-cache-slabs: 2

    # Cache sizes (adjust based on available memory)
    rrset-cache-size: 64m
    msg-cache-size: 32m

    # Prefetching
    prefetch: yes
    prefetch-key: yes

    # EDNS buffer size
    edns-buffer-size: 1232

    # Access control (allow local network)
    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow

    # Don't expose version
    hide-identity: yes
    hide-version: yes

    # Trust anchor for DNSSEC
    auto-trust-anchor-file: /var/lib/unbound/root.key

    # Serve expired responses while fetching new data
    serve-expired: yes
    serve-expired-ttl: 86400

    # Negative cache settings
    neg-cache-size: 4m

    # Private address ranges (for reverse DNS)
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
"""

    def generate_instructions(self, config: Dict[str, Any]) -> str:
        """Generate setup instructions based on configuration."""

        if config.get("deployment") == "docker":
            return self._generate_docker_instructions(config)
        else:
            return self._generate_bare_metal_instructions(config)

    def _generate_docker_instructions(self, config: Dict[str, Any]) -> str:
        """Generate Docker deployment instructions."""

        unbound_section = ""
        if config.get("enable_unbound", True):
            unbound_section = """
## Unbound Configuration

Unbound is configured as a recursive DNS resolver. This means:

- **No third-party DNS** - Queries go directly to authoritative nameservers
- **DNSSEC validation** - Responses are cryptographically verified
- **Privacy** - No single upstream DNS provider sees all your queries

The configuration is in `unbound/pi-hole.conf` and is optimized for home use.
"""

        dhcp_section = ""
        if config.get("dhcp_enabled", False):
            dhcp_section = f"""
## DHCP Configuration

Pi-hole is configured as your DHCP server with:

- **Range**: {config.get("dhcp_start", "192.168.1.100")} - {config.get("dhcp_end", "192.168.1.200")}
- **Gateway**: {config.get("dhcp_router", "192.168.1.1")}

**IMPORTANT**: Disable DHCP on your router before starting Pi-hole!

1. Log into your router's admin interface
2. Find DHCP settings (usually under LAN or Network)
3. Disable DHCP server
4. Save and apply changes
"""

        pihole_ip = config.get("pihole_ip", "192.168.1.2")

        return f"""# Pi-hole & Unbound Setup Guide

Generated by Pi-hole Wizard on {datetime.now().strftime("%Y-%m-%d")}

## Overview

This configuration deploys:

- **Pi-hole** - Network-wide ad blocker
- {'**Unbound** - Recursive DNS resolver' if config.get('enable_unbound', True) else 'Upstream DNS: ' + config.get('upstream_dns', 'cloudflare')}

## Prerequisites

- Docker and Docker Compose installed
- Static IP address ({pihole_ip}) configured on host
- Ports 53 (DNS) and 80 (Web UI) available

## Quick Start

```bash
# 1. Navigate to config directory
cd pihole-config

# 2. Review and edit .env file (set your password!)
nano .env

# 3. Start the containers
docker-compose up -d

# 4. Check status
docker-compose ps

# 5. View logs
docker-compose logs -f pihole
```

## Access Web Interface

Open http://{pihole_ip}/admin in your browser.

Password: (set in .env file)
{unbound_section}
{dhcp_section}
## Configure Your Network

### Option A: Router DNS (Recommended)

1. Log into your router
2. Find DNS settings (usually under WAN or Internet)
3. Set primary DNS to `{pihole_ip}`
4. Remove or leave blank any secondary DNS
5. Save and reboot router

### Option B: Per-Device

Configure DNS to `{pihole_ip}` on individual devices.

## Verify It's Working

```bash
# Test DNS resolution
nslookup google.com {pihole_ip}

# Test ad blocking (should return 0.0.0.0)
nslookup ads.google.com {pihole_ip}

# Check Pi-hole status
docker exec pihole pihole status
```

## Troubleshooting

### DNS not resolving
```bash
# Check if containers are running
docker-compose ps

# Check Pi-hole logs
docker-compose logs pihole

# Check Unbound logs (if enabled)
docker-compose logs unbound
```

### Slow DNS responses
```bash
# Test Unbound directly
docker exec unbound drill google.com @127.0.0.1 -p 5335
```

## Useful Commands

```bash
# Update Pi-hole
docker-compose pull && docker-compose up -d

# Update blocklists
docker exec pihole pihole -g

# Whitelist a domain
docker exec pihole pihole -w example.com

# Blacklist a domain
docker exec pihole pihole -b example.com

# View query log
docker exec pihole pihole -t

# Restart DNS
docker exec pihole pihole restartdns
```

## Getting Help

Use the AI Chat feature in Pi-hole Wizard for troubleshooting assistance.

## Resources

- [Pi-hole Documentation](https://docs.pi-hole.net/)
- [Unbound Documentation](https://unbound.docs.nlnetlabs.nl/)
- [Pi-hole + Unbound Guide](https://docs.pi-hole.net/guides/dns/unbound/)
"""

    def _generate_bare_metal_instructions(self, config: Dict[str, Any]) -> str:
        """Generate bare-metal installation instructions."""

        pihole_ip = config.get("pihole_ip", "192.168.1.2")

        return f"""# Pi-hole & Unbound Bare-Metal Setup Guide

Generated by Pi-hole Wizard on {datetime.now().strftime("%Y-%m-%d")}

## Prerequisites

- {config.get('os', 'Debian/Ubuntu').title()} operating system
- Root or sudo access
- Static IP address ({pihole_ip})

## Step 1: Install Pi-hole

```bash
# Download and run installer
curl -sSL https://install.pi-hole.net | bash
```

During installation:
- Select interface: `{config.get('network_interface', 'eth0')}`
- Upstream DNS: Select "Custom" and enter `127.0.0.1#5335`
- Install web interface: Yes

## Step 2: Install Unbound

```bash
# Install Unbound
sudo apt update
sudo apt install unbound -y

# Copy the generated config
sudo cp unbound/pi-hole.conf /etc/unbound/unbound.conf.d/

# Test configuration
sudo unbound-checkconf

# Restart Unbound
sudo systemctl restart unbound
sudo systemctl enable unbound

# Test it works
dig google.com @127.0.0.1 -p 5335
```

## Step 3: Configure Pi-hole to use Unbound

```bash
# Set custom DNS in Pi-hole
pihole -a setdns "127.0.0.1#5335"

# Restart Pi-hole DNS
pihole restartdns
```

## Step 4: Configure Your Network

Set your router's DNS to `{pihole_ip}`

## Verify Installation

```bash
# Check Pi-hole status
pihole status

# Test ad blocking
nslookup ads.google.com {pihole_ip}
```

Access web interface at: http://{pihole_ip}/admin
"""

    def _get_upstream_dns(self, config: Dict[str, Any]) -> str:
        """Get upstream DNS servers based on config."""
        dns_map = {
            "cloudflare": "1.1.1.1;1.0.0.1",
            "google": "8.8.8.8;8.8.4.4",
            "quad9": "9.9.9.9;149.112.112.112",
        }
        upstream = config.get("upstream_dns", "cloudflare")
        if upstream == "custom":
            return config.get("custom_dns", "1.1.1.1")
        return dns_map.get(upstream, "1.1.1.1;1.0.0.1")

    def _get_cidr(self, ip: str) -> str:
        """Get CIDR notation for reverse DNS."""
        parts = ip.split(".")
        return f"{parts[0]}.{parts[1]}.{parts[2]}.0/24"
