#!/bin/bash
#
# Pi-hole Wizard Installer
# This script installs Docker (if needed) and runs the Pi-hole Wizard web app
#
# Usage: curl -sSL https://pihole-wizard.com/install.sh | bash
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       Pi-hole Wizard Installer            ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    SUDO=""
else
    SUDO="sudo"
fi

# Detect architecture
ARCH=$(uname -m)
case $ARCH in
    x86_64)
        DOCKER_ARCH="amd64"
        ;;
    aarch64|arm64)
        DOCKER_ARCH="arm64"
        ;;
    armv7l|armhf)
        DOCKER_ARCH="armhf"
        ;;
    *)
        echo -e "${RED}Unsupported architecture: $ARCH${NC}"
        exit 1
        ;;
esac

echo -e "${GREEN}✓${NC} Detected architecture: $ARCH"

# Check for Docker
check_docker() {
    if command -v docker &> /dev/null; then
        echo -e "${GREEN}✓${NC} Docker is installed"
        return 0
    else
        return 1
    fi
}

# Install Docker
install_docker() {
    echo -e "${YELLOW}→${NC} Installing Docker..."

    # Use the official Docker install script
    curl -fsSL https://get.docker.com | $SUDO sh

    # Add current user to docker group
    if [ "$EUID" -ne 0 ]; then
        $SUDO usermod -aG docker $USER
        echo -e "${YELLOW}!${NC} Added $USER to docker group. You may need to log out and back in."
    fi

    # Start Docker service
    $SUDO systemctl enable docker
    $SUDO systemctl start docker

    echo -e "${GREEN}✓${NC} Docker installed successfully"
}

# Check for Docker Compose
check_docker_compose() {
    if docker compose version &> /dev/null; then
        echo -e "${GREEN}✓${NC} Docker Compose is available"
        return 0
    elif command -v docker-compose &> /dev/null; then
        echo -e "${GREEN}✓${NC} Docker Compose (legacy) is available"
        return 0
    else
        return 1
    fi
}

# Get local IP address
get_local_ip() {
    # Try multiple methods to get IP
    IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    if [ -z "$IP" ]; then
        IP=$(ip route get 1 2>/dev/null | awk '{print $7}' | head -1)
    fi
    if [ -z "$IP" ]; then
        IP="localhost"
    fi
    echo $IP
}

# Main installation
main() {
    # Check/install Docker
    if ! check_docker; then
        echo -e "${YELLOW}Docker not found. Installing...${NC}"
        install_docker

        # If we can't run docker without sudo, we need to use newgrp or re-login
        if ! docker info &> /dev/null; then
            echo ""
            echo -e "${YELLOW}══════════════════════════════════════════════════════════════════${NC}"
            echo -e "${YELLOW}  Docker installed! One more step needed on your Raspberry Pi.${NC}"
            echo -e "${YELLOW}══════════════════════════════════════════════════════════════════${NC}"
            echo ""
            echo -e "  Your user needs permission to run Docker commands."
            echo -e "  ${BLUE}Stay in this SSH session${NC} and run these two commands:"
            echo ""
            echo -e "  ${GREEN}1. newgrp docker${NC}"
            echo -e "  ${GREEN}2. curl -sSL https://pihole-wizard.com/install.sh | bash${NC}"
            echo ""
            echo -e "  ${YELLOW}(Don't close this terminal or log out - just run the commands above)${NC}"
            echo ""
            echo -e "${YELLOW}══════════════════════════════════════════════════════════════════${NC}"
            exit 0
        fi
    fi

    # Check Docker Compose
    if ! check_docker_compose; then
        echo -e "${RED}Docker Compose not found and couldn't be installed.${NC}"
        exit 1
    fi

    # Create installation directory
    INSTALL_DIR="$HOME/pihole-wizard"
    echo -e "${YELLOW}→${NC} Creating installation directory: $INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
    cd "$INSTALL_DIR"

    # Download docker-compose.yml
    echo -e "${YELLOW}→${NC} Downloading Pi-hole Wizard..."

    cat > docker-compose.yml << 'EOF'
# Pi-hole Wizard Web
# Generated by install.sh

services:
  pihole-wizard:
    image: ghcr.io/anishj9/pihole-wizard-web:latest
    container_name: pihole-wizard
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output:/app/output
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    restart: unless-stopped
EOF

    # For local development/testing, build from source instead
    # Uncomment below if you want to build locally:
    # git clone https://github.com/AnishJ9/pihole-wizard-web.git .
    # docker compose build

    # Pull the image
    echo -e "${YELLOW}→${NC} Pulling Docker image (this may take a few minutes)..."
    if docker compose pull 2>/dev/null || docker-compose pull 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Image downloaded"
    else
        echo -e "${YELLOW}!${NC} Could not pull image. Trying to build locally..."
        # Clone and build
        if command -v git &> /dev/null; then
            rm -rf docker-compose.yml
            git clone https://github.com/AnishJ9/pihole-wizard-web.git .
            docker compose build 2>/dev/null || docker-compose build
        else
            echo -e "${RED}Git not installed. Please install git and try again.${NC}"
            exit 1
        fi
    fi

    # Start the wizard
    echo -e "${YELLOW}→${NC} Starting Pi-hole Wizard..."
    docker compose up -d 2>/dev/null || docker-compose up -d

    # Wait for startup
    echo -e "${YELLOW}→${NC} Waiting for wizard to start..."
    sleep 3

    # Get the IP
    LOCAL_IP=$(get_local_ip)

    echo ""
    echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Pi-hole Wizard is running!${NC}"
    echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  Open this URL in your browser:"
    echo ""
    echo -e "  ${BLUE}http://${LOCAL_IP}:8080${NC}"
    echo ""
    echo -e "  Or if you're on the same device:"
    echo -e "  ${BLUE}http://localhost:8080${NC}"
    echo ""
    echo -e "${GREEN}══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  ${YELLOW}Tip:${NC} You can open this URL on your phone, tablet,"
    echo -e "  or any device connected to your network."
    echo ""
    echo -e "  To stop the wizard later: ${GREEN}cd $INSTALL_DIR && docker compose down${NC}"
    echo ""

    # Try to open browser (works on desktop Linux, ignored on headless)
    if command -v xdg-open &> /dev/null; then
        xdg-open "http://${LOCAL_IP}:8080" 2>/dev/null &
    elif command -v open &> /dev/null; then
        open "http://${LOCAL_IP}:8080" 2>/dev/null &
    fi
}

# Run main function
main
